# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftl < Formula
  desc "FTL is a platform for building distributed systems that are safe to operate, easy to reason about, and fast to iterate and develop on."
  homepage "https://github.com/block/ftl"
  version "0.484.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/block/ftl/releases/download/v0.484.0/ftl-0.484.0.darwin-amd64.tar.gz"
      sha256 "99af6aac11a83014c753a356c9115994890ba147dcf9274504c610ba86d360a7"

      def install
        bin.install "ftl"
        bin.install "ftl-language-go"
        bin.install "ftl-language-java"
        bin.install "ftl-language-kotlin"
        bin.install "ftl-sqlc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/block/ftl/releases/download/v0.484.0/ftl-0.484.0.darwin-arm64.tar.gz"
      sha256 "0c9069957e75348f997777e95965eb89172adeb20b2d4066498aba7261d8f6be"

      def install
        bin.install "ftl"
        bin.install "ftl-language-go"
        bin.install "ftl-language-java"
        bin.install "ftl-language-kotlin"
        bin.install "ftl-sqlc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/block/ftl/releases/download/v0.484.0/ftl-0.484.0.linux-amd64.tar.gz"
        sha256 "e3ac0cb17f9e2df580bb59e4b04e033a3cd89e886375eff2ce3ace4840914cb0"

        def install
          bin.install "ftl"
          bin.install "ftl-language-go"
          bin.install "ftl-language-java"
          bin.install "ftl-language-kotlin"
          bin.install "ftl-sqlc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/block/ftl/releases/download/v0.484.0/ftl-0.484.0.linux-arm64.tar.gz"
        sha256 "9d9900c0908348847706650af9e28c13aabecac7e033e716f9212036ae801f68"

        def install
          bin.install "ftl"
          bin.install "ftl-language-go"
          bin.install "ftl-language-java"
          bin.install "ftl-language-kotlin"
          bin.install "ftl-sqlc"
        end
      end
    end
  end
end
